Mobile First Setup
enocol/MobileFirst pull request #1
Opened 2023-06-02 11:14 UTC by enocol

This is my first Mobile website portfolio setup.

2023-06-02 12:53 UTC, mahbubul14 requested changes
Hi @enocol,

Good job so far! :+1: 
There are some issues that you still need to work on to go to the next project but you are almost there!

# Required Changes ♻️

- [ ] Pull Request should have a descriptive title telling you what changes are inside and a short summary describing introduced changes in more detail.
![pull](https://github.com/enocol/MobileFirst/assets/70483835/83429e68-d475-4173-8a2e-2dc4ca2d8ef9)


- [ ] Kindly check the inline comments under the review. :arrow_down: 

###  To Highlights
:heavy_check_mark: No linter error.
:heavy_check_mark: Proper Github flow used.
:heavy_check_mark: Descriptive PR title & description.

### Optional suggestions

Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better.

- [ ] The commit message should be written in the imperative tense and the first letter should also be capitalized. `Ex: "Fix bug" instead of "fix bug".` [For more details...](https://www.freecodecamp.org/news/level-you-up-to-awesome-commit-messages-a85558cb90e8)


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification. You can also reach me on [slack](https://microverse-students.slack.com/team/U01J39GL614)

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2023-06-02 12:53 UTC, mahbubul14 commented on index.html
> +      <img class="image" src="./images/logo.png" alt="" />
- [ ] The logo on the left should have a link (`a` tag). Kindly work on it. :+1:

2023-06-02 12:53 UTC, mahbubul14 commented on index.html
> +    </header>
- [ ] The hamburger button on the right should have a `nav` tag. Kindly work on it. :+1:

2023-06-02 12:53 UTC, mahbubul14 commented on index.html
> +    </footer>
- [ ] The container of the section is a `section` tag. It should be wrapped in a `section` tag. You can also remove the `footer` tag from here because this is not a footer of your page. :+1:

2023-06-02 12:53 UTC, mahbubul14 commented on index.html
> +    </footer>
- [ ] The list of icons uses a `ul` tag to group them, and `li` per icon; each icon has a link (`a` tag). :+1:

2023-06-02 12:53 UTC, mahbubul14 commented on index.html
> +    </p>
- [ ] Your website should look exactly like the design (e.g. font, colors, images, text, margins) using the templates in Figma. Please work on it and  make your design close to the Figma design. :+1: 

Your design             |  Figma Design
:-------------------------:|:-------------------------:
![yourdesign](https://github.com/enocol/MobileFirst/assets/70483835/0ed1dc14-22c9-4423-9799-c2e4bbf12510) | ![figma](https://github.com/enocol/MobileFirst/assets/70483835/3521d692-2a68-4f04-b80f-3de225eb7d33)

2023-06-02 12:53 UTC, mahbubul14 commented on README.md
> +<p align="right">(<a href="#readme-top">back to top</a>)</p>
- [ ] You have used the correct template for the readme but forget to customize it according to your project. Please work on it. :+1:

2023-06-03 14:47 UTC, zeff96 requested changes
### Status: CHANGES REQUIRED ♻️ ♻️ ♻️ 
Hi @enocol , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![almost](https://media2.giphy.com/media/t8YPf3ACKeouLzEIvr/200w.webp?cid=ecf05e472tcbmdjpbny56ml3cf7k0pg8u6crasxfpz9ehtdr&ep=v1_gifs_search&rid=200w.webp&ct=g)


 ## Highlights
 
 ✅  Linters passing


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-03 14:47 UTC, zeff96 commented on README.md
> +</details>
- [ ] I would advise you to customize this section with information relevant to your project and remove sections that aren't relevant to your project.

```suggestion
<details>
  <summary>Client</summary>
  <ul>
    <li>HTML</li>
     <li>CSS</li>
  </ul>
</details>
```

2023-06-03 14:47 UTC, zeff96 commented on README.md
> +- [Live Demo Link](https://google.com)
- [ ] I would advise you to deploy your project with GitHub pages and then update this link with a working demo link. You can use this [link](https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site) as a guidance on how to deploy to GitHub pages

2023-06-03 14:47 UTC, zeff96 commented on README.md
> + -->
- [ ] Kindly provide your users and other developers with a proper way to run your project on their machines. This information is critical to non-technical users who might be your potential clients

2023-06-03 14:47 UTC, zeff96 commented on README.md
> +--->
- [ ] Kindly provide the correct GIT URL to clone your project. how does that sound?

```suggestion
Clone this repository to your desired folder:
```sh
  cd my-folder
  git@github.com:enocol/MobileFirst.git
```
```

2023-06-03 14:47 UTC, zeff96 commented on README.md
> +
- [ ] Kindly customize this section according to your project requirements and remove the section that does not currently apply to your project.

2023-06-03 14:47 UTC, zeff96 commented on README.md
> + -->
- [ ] Kindly remove this section from your project if it hasn't been deployed yet. This makes your readme looks professional

2023-06-03 14:47 UTC, zeff96 commented on README.md
> +👤 **Author1**
- [ ] I would recommend using your name as it is the recommended way

2023-06-03 14:47 UTC, zeff96 commented on README.md
> +
- [ ] Kindly customize this part with your social media details and remove `author 2` part as your currently the solo contributor to this project.

2023-06-03 14:47 UTC, zeff96 commented on README.md
> +_NOTE: we recommend using the [MIT license](https://choosealicense.com/licenses/mit/) - you can set it up quickly by [using templates available on GitHub](https://docs.github.com/en/communities/setti
- [ ] Kindly remove this section from your project as this makes your readme looks unprofessional

2023-06-03 14:47 UTC, zeff96 commented on README.md
> +I would like to thank...
- [ ] I would advise you to use complete statements as this makes your readme looks more professional.

2023-06-03 14:47 UTC, zeff96 commented on index.html
> +      </div>
- [ ] As mentioned by the previous reviewer, the project requires you to enclose this section under `header` tag and wrap the hamburger button with `nav`

```suggestion
    <header>
      <a href="/">My Logo</a>
      <nav>
        <img src="./images/hamburger.png" alt="" class="image">
      </nav>
    </header>
```

2023-06-03 14:47 UTC, zeff96 commented on index.html
> +        Glad to see you!
- [ ] this text should be wrapped using `h1` as per the project requirements. Kindly make that change.

2023-06-03 14:47 UTC, zeff96 commented on main.css
> +  font-family: 'Times New Roman', Times, serif;
- [ ] According to the Figma design. The font family should be Poppins. Kindly adjust your project according to the Figma design.

2023-06-03 14:47 UTC, zeff96 commented on main.css
> +}
- [ ] As mentioned by the previous reviewer, Kindy adjust your project to match the figma design.

your design
![Screenshot 2023-06-03 at 16 48 55](https://github.com/enocol/MobileFirst/assets/112261237/997ce8c0-bbb4-466e-99f8-3609b469d264)

Figma design
![Screenshot 2023-06-03 at 16 51 37](https://github.com/enocol/MobileFirst/assets/112261237/cceb6955-8738-41ce-b01a-c0c2e807c32c)

2023-06-03 14:58 UTC, enocol commented on README.md
> +</details>
please can you call me to help me do exactly what changes need doing in this ReadMe? Last time valentine call and help me with it. The changes you are asking I am not very sure what it is because i have not yet understood properly how to deal wit this READMe template. I am on my desk until 6pm UK time

2023-06-03 15:01 UTC, zeff96 commented on README.md
> +</details>
@enocol, kindly call me on zoom. search for Adeka and call

2023-06-03 18:37 UTC, AbdusSattar-70 requested changes
## REQUIRED CHANGES  ♻️ 
Hi @enocol , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
- PROFESSIONAL README
- NO LINTER ERROR
- FOLLOW GITHUB WORKFLOWS
![AlmostGIF](https://github.com/NoelLincoln/mportfolio/assets/118761303/e928691c-a510-4e83-99f5-25fbc05e05cf)

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-03 18:37 UTC, AbdusSattar-70 commented on main.css
> +  font-family: 'Times New Roman', Times, serif;
As highlighted by the [previous reviewer](https://github.com/enocol/MobileFirst/pull/1/files#r1215578152), it appears that no changes have been made. Please take their feedback into consideration and make the necessary revisions before resubmitting the pull request.

- [ ] Your design:
![yourD](https://github.com/enocol/MobileFirst/assets/118761303/f7a0dfb5-68ee-4405-b4e6-856cde2b7668)

- [ ] 
![Screenshot 2023-06-04 003433](https://github.com/enocol/MobileFirst/assets/118761303/9f124f56-6ec4-4200-be61-8430fb6a523d)

2023-06-03 18:37 UTC, AbdusSattar-70 commented on index.html
> +        Glad to see you!
As highlighted by the[ previous reviewer](https://github.com/enocol/MobileFirst/pull/1/files#r1215576852)r, it appears that no changes have been made. Please take their feedback into consideration and make the necessary revisions before resubmitting the pull request.

2023-06-03 18:37 UTC, AbdusSattar-70 commented on index.html
> +      </div>
- [ ] As highlighted by the previous reviewer, it appears that no changes have been made. Please take their feedback into consideration and make the necessary revisions before resubmitting the pull request.
- [ ] I appreciate your efforts in incorporating the <`nav>` tag into your project. To adhere to HTML5 structural guidelines, it is recommended to place the `<nav>` element inside the `<header>` tag. This ensures a more semantic and organized structure for your HTML document. 
- [ ] By following this practice, you can enhance the overall code structure and maintain compliance with HTML5 standards.
- [ ] 
![Screenshot 2023-06-04 002921](https://github.com/enocol/MobileFirst/assets/118761303/46351c76-4b93-4a7a-a2cd-9cd5a288d075)

- [ ] For more information please [check it](https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Document_and_website_structure)

2023-06-03 18:55 UTC, enocol commented on main.css
> +  font-family: 'Times New Roman', Times, serif;
I think it will be very helpful if you can call me now. pinpoint and help me on sorting what your change request requires. Thanks.

2023-06-03 19:11 UTC, enocol commented on index.html
> +      </div>
I spoke to the previous reviewer before you and we did some changes. I am not very sure which changes you mean. I will wait for your call but i have sent you an zoom invitation so that we can speak  and look into your change request on the a zoom call

2023-06-04 13:44 UTC, AbdusSattar-70 commented on main.css
> +  font-family: 'Times New Roman', Times, serif;
> I think it will be very helpful if you can call me now. pinpoint and help me on sorting what your change request requires. Thanks.

- [ ] @enocol Thanks for your query, It would be better if you read all the suggestions made by previous reviewers.

- [ ]  By following the project requirements and reading[ this](https://github.com/enocol/MobileFirst/pull/1/files#r1215714084) suggestions you may understand that.

2023-06-07 11:40 UTC, joel-kalema reviewed
Hi @enocol 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request  🛑 

![pirates-of-the-caribbean-johnny-depp](https://user-images.githubusercontent.com/57408419/242635897-074a8afb-6646-4281-8ff9-8390f857a9c5.gif)


- [ ] You have submitted a project that doesn't have a professional README


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @joel-kalema in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-06-07 12:20 UTC, enocol commented
hi @joel-kalema . Thank you for your review. Please could you call me so that we could fix this problem? I have customized the ReadMe file to match my project. I am not really sure what in the Readme to fix. It was another code reviewer who had helped me prepare the ReadMe file.

2023-06-07 12:21 UTC, closed without merging