Added Projects and Abouts Sections
enocol/MobileFirst pull request #3
Opened 2023-06-08 17:42 UTC by enocol

Made some changes and added the following new sections.
1) Added the About section.
2) Added the Projects section.
3) Added the language and Skill pages as well.

2023-06-08 18:38 UTC, Bantealem reviewed
Hi @enocol 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has a Lnters error. Please resolve the Lnters error and request a review.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-06-08 20:05 UTC, bobb-Rob reviewed
## STATUS: CHANGES REQUIRED ♻️
Hi @enocol, 

Good job so far! 👏👏👏 
There are some issues that you still need to work on to go to the next project but you are almost there!  😃 
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>
![](https://camo.githubusercontent.com/34482800e1b92cb79ddca06edb4051edc407cb190f896e1e949e596aa9073851/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f556461535559436c723932636a57706556782f67697068792e676966)

## Highlights
✅ No Linter error
✅ Correct use of GitHub flow
✅ Very descriptive Pull Request(PR)

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-08 23:09 UTC, enocol commented on index.html
> +        </div>
@bobb-Rob Images have been adjusted accordingly. Thanks

2023-06-08 23:10 UTC, enocol commented on index.html
> +          <button class="button">Get my resume</button>
@bobb-Rob Now adjusted accordingly

2023-06-08 23:11 UTC, enocol commented on index.html
> +          </div>
@enocol This has been implemented accordingly.

2023-06-08 23:12 UTC, enocol commented on index.html
> +      </div>
Adjustments have been made accordingly.

2023-06-09 00:32 UTC, sebalp100 requested changes
Hi @enocol , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![dog](https://github.com/enocol/MobileFirst/assets/111214189/4edcd5fb-854a-4222-beaa-f1daed15cf88)


 ## Highlights

✔️ Good implementation of hx tags
✔️ Good use of li elements

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-09 00:32 UTC, sebalp100 commented on index.html
> +          <div class="details">
As the previous reviewer mentioned, kindly stick to the Figma design as much as possible. Some of your sections don't have the correct margin or border-radius:

**Your design:**

![separation](https://github.com/enocol/MobileFirst/assets/111214189/01b2849d-f656-4597-9cda-9e6c283514c2)


**Fima Template with margin and border (your project should look like this):**

![homef2](https://github.com/enocol/MobileFirst/assets/111214189/c3c4a987-bea3-48c9-81f9-716c123712f5)



You are using the incorrect margin for your cards.

**Your design (incorrect margin):**

![margins2](https://github.com/enocol/MobileFirst/assets/111214189/029dca5a-8c8b-46b6-9c06-91e4d0a951fd)

**Figma template margin (correct margin):**

![margins](https://github.com/enocol/MobileFirst/assets/111214189/40eaed99-b2b6-4769-82f7-eaf68f77321a)


The top of your About me section doesn't have the correct space between the "About myself" title and the background. You are also missing the top-right border-radius:

**Your design (incorrect margin and no border-radius):**

![marginandborder2](https://github.com/enocol/MobileFirst/assets/111214189/f119f7d3-3ce9-40d5-b618-71cea291f931)


**Figma template (correct margin and border):**

![marginandborder](https://github.com/enocol/MobileFirst/assets/111214189/0b08a454-abff-4685-8d15-283c1a972b7f)

Your design seems to be missing the bottom margin after the skills arrow compared to the Figma template. You also seem to have an extra list of technologies that don't show up on the Figma design:

**Your design:**

![missingmargins2](https://github.com/enocol/MobileFirst/assets/111214189/d804eaae-e7c4-4cf6-ad1b-fb51efb5d6da)

**Figma template:**

![missingmargins](https://github.com/enocol/MobileFirst/assets/111214189/760a0e65-30f3-4ad5-b1ac-3067e51ca817)


Kindly fix all these issues. This will show that you are capable of following a Figma design and have great attention to detail 👍

2023-06-09 00:32 UTC, sebalp100 commented on index.html
>    </body>
[OPTIONAL] There seems to be an element generating a horizontal scrollbar. I think it will be good to fix this issue. The previous reviewer didn't mention this but I **highly** recommend you to fix it. It will help with your user's experience and look more professional 💯

![horiz](https://github.com/enocol/MobileFirst/assets/111214189/986320b0-4d08-4e0b-b0b8-766da75e8485)

2023-06-09 00:32 UTC, sebalp100 commented on index.html
> +            what you see and have a project you need coded, don't hesitate to
[OPTIONAL] I think it would be a good idea to wrap your about myself with a Section tag. Your previous reviewer didn't mention this but I **highly** recommend you to implement it. This will make your code more organized.

2023-06-10 07:58 UTC, shella12 requested changes
Hi @enocol, 

Great work on making the changes requested by a previous reviewer 👏 👏 👏 👏 
You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet. You are almost there...

<img src="https://media1.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Highlights

- Implemented rounded corners ✅ 
- Added bottom margin for `About me ` categories  ✅   

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-10 07:58 UTC, shella12 commented on index.html
> +        </ul>
- [ ] As suggested by all the previous reviewers please remove this list of languages (HTM, CSS, JavasScript) from` About section` as its extra and is not part of the design.

<img width="292" alt="244854773-b3c5b3f0-480e-4981-b0ec-b35038aa3cf0" src="https://github.com/enocol/MobileFirst/assets/44798044/ecb19c93-69f2-4d00-8aae-624359ebde9f">

2023-06-10 07:58 UTC, shella12 commented on index.html
> +    <div class="grid-container">
- [ ] [OPTIONAL] Please use a `main `tag instead of` div `tag here because `<main>` element represents the main content inside the body of the page, and `<div>` is a generic container that groups content. So using main would be semantically more appropriate.

2023-06-10 07:58 UTC, shella12 commented on index.html
> +          <li>CSS</li>
- [ ] As suggested by the previous reviewer please wrap all your projects in one section tag and use `grid `to align your cards as it is the requirement of the project 

> In order to lay out the elements in "Works" section you should use CSS Grid and Flexbox combined (it is mandatory that you use both). Use CSS Grid in the main container that contains all of the cards and use Flexbox to lay out an individual card.

2023-06-10 07:58 UTC, shella12 commented on style.css
> +}
- [ ] As mentioned by previous reviewers please remove the extra margin from the sides of your project to make your design look more professional and match the provided [figma design](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?type=design&node-id=0-1&t=Jkto5aLV5YWl8FSX-0). 

|Your design| Figma design|
|----|----|
|<img width="376" alt="Screenshot 2023-06-10 at 12 30 54 PM" src="https://github.com/enocol/MobileFirst/assets/44798044/abfa7199-cb02-4bf7-9af1-e6bba5f33d10">|<img width="300" alt="Screenshot 2023-06-10 at 12 44 50 PM" src="https://github.com/enocol/MobileFirst/assets/44798044/ce708825-3077-4922-b36a-e83560196126">|

2023-06-10 07:58 UTC, shella12 commented on index.html
> +        <h2 class="about">About Myself</h2>
- [ ]  [OPTIONAL] I would highly recommend you to consider [OPTIONAL] suggestions of the previous reviewer [here](https://github.com/enocol/MobileFirst/pull/3#discussion_r1223672655) as they are suggestations are really going to help you code clean and implement standard practices.

2023-06-10 07:58 UTC, shella12 commented on index.html
> +            </li>
- [ ] [OPTIONAL] The technology in language category(i.e., "JavasScript", "HTML" and "CSS") do not need to use hyper link `a` tag as they are just a list of languages. You don't expect people to click a language and navigate to somewhere.

2023-06-10 08:06 UTC, enocol commented on index.html
> +        </ul>
OK. That's what I have on the template in Figma but if you have asked me to remove it, I will remove it. Thanks

2023-06-10 08:08 UTC, enocol commented on index.html
> +        </ul>
@shella12 I am removing it based on your request but just to mention that that's what I have on the template in Figma. Thanks

2023-06-10 08:13 UTC, enocol commented on index.html
> +            </li>
@shella12 This was what another code reviewer had asked me to do. The project did not have that as a link until a reviewer asked me to include an "a" tag.

2023-06-10 08:30 UTC, enocol commented on index.html
> +          <div class="details">
![image](https://github.com/enocol/MobileFirst/assets/129378066/1378563c-d691-413a-a5d8-e1f7d1ecbe3e)

2023-06-10 08:31 UTC, enocol commented on index.html
> +        </ul>
![image](https://github.com/enocol/MobileFirst/assets/129378066/a388a5fb-9f03-40df-9e45-50efb07d09fc)

2023-06-10 09:24 UTC, enocol commented on index.html
> +          <li>CSS</li>
![image](https://github.com/enocol/MobileFirst/assets/129378066/52977f12-e671-49ec-8c4a-45776ef2551f)

2023-06-10 09:31 UTC, enocol commented on index.html
> +          <li>CSS</li>
@shella12 I have made changes as recommended and I have also highly considered the  Optional recommendations. I will implement them as soon as I become relaxed when this project gets approved.  I will personally show you the Optional modifications when I get these fixed tomorrow then bring them to you on Monday if that's okay with you.

2023-06-10 09:40 UTC, enocol commented on index.html
> +            </li>
The <a> tag has now been removed

2023-06-10 09:46 UTC, enocol commented on index.html
> +            what you see and have a project you need coded, don't hesitate to
I have highly taken into consideration the Optional recommendations. May I continue to implement these when my project is approved and then in a more relaxed state? I am highly worried about my progress at this time. I will rather implement these optional recommendations in a more relaxed state otherwise I may break my code being stressed now. Thank you very much.

2023-06-10 13:53 UTC, Alusp approved these changes
Hi @enocol , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![congratulations](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExeWx6MDdrMW00NHp0MW0xczFxem92cDJ2MGd6ZzkzMGo0azN0ZDVjbSZlcD12MV9naWZzX3NlYXJjaCZjdD1n/qx8pi39Lwm9Xm2audb/giphy.gif)

## Highlights

- [ ] Good Commit History :green_circle: 
- [ ] Good Github Flow :green_circle: 
- [ ] Good PR Summary :green_circle: 
- [ ] No Linter Errors :green_circle: 


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-10 13:53 UTC, Alusp commented on style.css
> +  border: 1px solid #dfe1e6;
[OPTIONAL] Please ensure that your botton border color matches the given design, you can use `#6060ff` instead of `#dfe1e6`

2023-06-10 13:53 UTC, Alusp commented on style.css
> +}
[OPTIONAL]  Please ensure that you fix the spacing between your Canopy item, it is very important to adhere to the given design and requirement.

Below is an illustration of the difference: :arrow_down: 

<table>
    <tr>
      <td>Your Design</td>
      <td>Figma Design</td>
    </tr>
    <tr>
      <td>

![Student Canopy](https://github.com/enocol/MobileFirst/assets/43528594/79b8ad70-d9af-4fe1-9288-c6326fdacbde)

</td>
      <td>

![Figma Design Canopy](https://github.com/enocol/MobileFirst/assets/43528594/e5bf9b0d-7e67-490f-9fff-350cf768d576)

</td>
    </tr>
  </table>

2023-06-10 13:53 UTC, Alusp commented on index.html
> +        </ul>
[OPTIONAL] Please ensure that you add the arrow icons in your technologies section as shown in the design below.

<table>
    <tr>
      <td>Your Design</td>
      <td>Figma Design</td>
    </tr>
    <tr>
      <td>

![Student arrow](https://github.com/enocol/MobileFirst/assets/43528594/38c524bb-51c0-4d23-ab9f-c60efcbb69c7)

</td>
      <td>

![Figma Arrows](https://github.com/enocol/MobileFirst/assets/43528594/8b0f2dbb-0476-4cec-987b-2eb1f626ab6a)
</td>
    </tr>
  </table>

- [ ] Please also take into consideration about how you name  your classes, As projects grow and evolve, having descriptive class names simplifies maintenance and scalability. When you or others revisit the code later, clear and meaningful class names make it easier to identify and modify specific elements or styles without needing to decipher their purpose. This helps save time and reduces the risk of introducing unintended side effects when making changes. :smiley:

2023-06-10 14:15 UTC, merged