Add desktop version of the Mobile Website
enocol/MobileFirst pull request #5
Opened 2023-06-15 17:05 UTC by enocol

2023-06-15 17:52 UTC, Bantealem reviewed
Hi @enocol, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that hasn't a PR summary. Please list your achievements in this milestone so a reviewer can see what you have done. 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-06-15 19:17 UTC, Shisui6 requested changes
Hi @enocol, 

# Requires Changes 🍀
You have done a great job so far!👏👏
You still need to work on a few issues before moving on to the next project, but you're almost there🪲!

## Highlights🎯
- Descriptive PR title and summary ✅
- Follows Github flow ✅
- Good commit messages ✅

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions 🪶
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code._

You can also consider the following:

N/A

Cheers and Happy coding!🍻💻

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid, unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561), you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-15 19:17 UTC, Shisui6 commented on style.css
> +  }
Kindly update your about myself section to match the figma design better🙏

Your design:
<img width="946" alt="image" src="https://github.com/enocol/MobileFirst/assets/37116322/703ad5d9-9681-4a7a-9c0c-fe6cb1797ebc">

Figma design:
<img width="559" alt="image" src="https://github.com/enocol/MobileFirst/assets/37116322/f1bf7fa1-d3ff-4253-a797-dad9da368799">

A few things to note:
- Please remove the border radius applied to all corners of the section as it is not present in the figma design. Please apply the border radius only on the top right corner
- There is a grey divider between the about section and the contact me section which is not present in the figma design. Please remove it
- Please increase the font size and weight of the about myself text and make sure all the text elements on the left side are right aligned
- Please add the arrow icons on the left side of the section
- Please increase the font weight of the categories `languages, frameworks and skills` and increase the vertical padding for each category
- Please update the technologies `html, CSS and js` to have a vertical flow instead of a horizontal flow

2023-06-15 19:17 UTC, Shisui6 commented on style.css
> +  }
Kindly update your contact section to match the figma design better🙏

Your design:
<img width="465" alt="image" src="https://github.com/enocol/MobileFirst/assets/37116322/9c050652-1726-4eef-9db7-ba7c49c57006">

Figma design:
<img width="496" alt="image" src="https://github.com/enocol/MobileFirst/assets/37116322/5f1958fa-3b08-46da-acb8-55123f7b1de3">

A few things to note:
- Kindly adjust your background image and color to match the figma design
- Kindly update your paragraph text to have less width and to be white
- Kindly remove the border radius on the form input elements and increase the width
- Kindly make sure the get in touch button is centralized

2023-06-16 15:46 UTC, enocol commented on style.css
> +  }
removed now

2023-06-16 17:06 UTC, enocol commented on style.css
> +  }
Done

2023-06-16 18:22 UTC, skyv26 requested changes
## Hi @enocol, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

## STATUS: REQUIRE CHANGES 🔴 

![](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExYTY5MTMxNDUzNWFmNjU5MmFjOWZjY2IyMDIyY2RhNWFlYmU4NjdlNCZlcD12MV9pbnRlcm5hbF9naWZzX2dpZklkJmN0PWc/Xfb7kQ0VhUIrpiuGx1/giphy.gif)

## Highlights
- Good **PR** title ✅ 
- Descriptive *PR* description ✅ 
- Implement the features ✅ 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

#### Cheers, and Happy coding!👏👏👏

## ⚠️  WARNING ⚠️ 
**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

## Have any doubt ❓ 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @skyv26 in your question so I can receive the notification. You can also follow me on the below platforms

<table>
<tr>
<td>

<a href="https://github.com/skyv26">
   <img src="https://img.shields.io/badge/GitHub-100000?style=for-the-badge&logo=github&logoColor=white" alt="@skyv26" />
</a>

</td>
<td>

<a href="https://www.linkedin.com/in/skyv2022/">
   <img src="https://img.shields.io/badge/LinkedIn-0077B5?style=for-the-badge&logo=linkedin&logoColor=white" alt="linkedin-skyv2022" />
</a>

</td>
<td>

<a href="https://twitter.com/vrma_aakash">
   <img src="https://img.shields.io/badge/Twitter-1DA1F2?style=for-the-badge&logo=twitter&logoColor=white" alt="@vrma_aakash" />
</a>

</td>
<td>

<a href="https://www.instagram.com/skybrel/">
   <img src="https://img.shields.io/badge/Instagram-E4405F?style=for-the-badge&logo=instagram&logoColor=white" alt="@skybrel" />
</a>

</td>
<td>

<a href="https://www.frontendmentor.io/profile/skyv26">
   <img src="https://user-images.githubusercontent.com/66476329/243158690-61eb1021-fbb6-464d-b841-a09c4caa156e.png" alt="@skybrel" />
</a>

</td>
</tr>
</table>

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-16 18:22 UTC, skyv26 commented on style.css
> +  .card-6 {
- [ ] Well done 👏🏻 , you did an awesome job by implementing the changes as per the previous code reviewer's request 👍🏻 but you didn't implement the changes properly, as I can see that your design doesn't have enough space at both left and right-hand-side of the project cards. Kindly adhere to the project requirement because the design given in **Figma** is a professional-looking design you are a reference guide which is helping you to make your own portfolio using the design, so please follow it properly and have a look at the below-attached design comparison image and table.

### Requirement
![image](https://user-images.githubusercontent.com/66476329/236188683-4224cc77-237d-413d-9942-91297c87687b.png)

### Design Comparison
<table>
<tr>
<th>Figma Design</th>
<th>Your Design</th>
</tr>
<tr>
<td>

![Screenshot from 2023-06-16 23-31-58](https://github.com/enocol/MobileFirst/assets/66476329/351430c1-84a9-4af2-b422-4e2633a894c2)

</td>
<td>

![Screenshot from 2023-06-16 23-31-13](https://github.com/enocol/MobileFirst/assets/66476329/2d10b90b-67d9-4956-b6ab-4e9a15186515)

</td>
</tr>
</table>

2023-06-16 23:53 UTC, brainconnect93 requested changes
### Hi @enocol, 👋 

# STATUS: Changes Required :recycle:

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media.tenor.com/isiLRnxz3zwAAAAM/cat-driving-serious.gif" width="500px" height="300px">

## Good Points 👍

- Descriptive Pull Request title & summary. ✔️
- No Linter errors ✔️
- Good use of Github flow ✔️
- Work on the desktop view as requested by the reviewer 
- Media query properly used

### Changes Required

- [x]  _Please check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me on( @brainconnect93 ) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-16 23:53 UTC, brainconnect93 commented on index.html
> +                <p>Javascript</p>
- [ ] Great effort working the changes requested by the previous reviewers, but i notice the emphasis on the aspect of following project requirement and Figma design as strict as possible is not taking cognizance of, Currently you have implemented the arrow icon missing in the languages part of the `about section. But the design you have there does not look like what we have in the Figma design. Kindly work on it and be sure you have a good replica of the Figma design.
- [ ] Also in the mobile view, I would kindly suggest you work on the images in the project cards as it does not fit properly inside the cards.

Below 👇 

| Figma Design  | Your Design |
| ------------- | ------------- |
| ![abt-new](https://github.com/enocol/MobileFirst/assets/78634841/43879ce9-5b22-4de4-8140-c79f1ac4f0b3) | ![eno-abt](https://github.com/enocol/MobileFirst/assets/78634841/a96914f6-7da1-4f48-9124-0fa6dc61cf9e) |

2023-06-17 05:53 UTC, enocol commented on index.html
> +                <p>Javascript</p>
@brainconnect93 could you call me and we discuss these changes, please? I have exhausted my review by adjusting what other reviews say but new reviewers keep asking different things. Maybe by talking directly, you could help to show me exactly where to fix it. it's a learning process. for me

2023-06-17 06:39 UTC, enocol commented on index.html
> +                <p>Javascript</p>
@brainconnect93  I thought I had a good replica. How much in percentage could you say this replica has to resemble the original in your opinion? 100%? Do I have to have a 100% match?

2023-06-17 07:52 UTC, usorfaitheloho approved these changes
Hi @enocol  👋,

# STATUS: APPROVED 🕺🥳 

Congratulations🍾🥳!! Your project is ready for presentation!  There is nothing else to say other than... it's time to merge it :shipit: 

![](https://media.giphy.com/media/l49JNZ87F3AmPoH0A/giphy.gif)

Good luck! 🎉 


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-17 08:06 UTC, merged