Add mobile menu and Links
enocol/MobileFirst pull request #6
Opened 2023-06-26 19:54 UTC by enocol

- Add Hamburger menu mobile version.
- Include a Link to the menu to other pages of the site.
- Use JavaScript to call the mobile menu when the hamburger is clicked and close it
- -Install Eslint for JavaScript

2023-06-26 21:51 UTC, Strangeal requested changes
Hi @enocol and @BiancaMe, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![Alt Text](https://media.giphy.com/media/t8YPf3ACKeouLzEIvr/giphy.gif)
## Highlights
Correct use of GitHub Flow ✅
Well-structured files ✅
Descriptive PR title with a great summary ✅

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-26 21:51 UTC, Strangeal commented on style.css
> +}
- [ ] Great job on implementing the hamburger menu as specified in the project requirement! 👏 However, there is a minor UI issue 🐞 that we need to address and fix as it would help make your design look more professional and also create a good user experience.
  - Kindly consider styling your close button to match that of the `Figma` design as it currently doesn't. See below for more details:

<table>
<tr>
<th align=“middle”>Figma design</th>
<th align=“middle”>Your design</th>
</tr>
<tr>
<td>
<img width="368" alt="Screenshot 2023-06-26 at 21 39 45" src="https://github.com/enocol/MobileFirst/assets/107192076/f5d77fc7-f732-4d54-861b-3774eb5dc38a">
</td>
<td>
<img width="374" alt="Screenshot 2023-06-26 at 21 38 44" src="https://github.com/enocol/MobileFirst/assets/107192076/169aa5f3-10df-4748-a79b-213416a30d5d">
</td>
</tr>
</table>

2023-06-26 21:51 UTC, Strangeal commented on style.css
> +
- [ ] Kindly note that it's important to style your design to match that of the `Figma` design as paying attention to design details showcases your attentiveness and precision, which are crucial skills for a developer. By aligning your implementation with the specified design, you demonstrate your ability to faithfully translate visual concepts into functional code. Kindly consider the below suggestions:
  - Your nav items `font-size` and `weight`  doesn't match that of the `Figma` design so please consider adjusting them accordingly as this will help you to create a good user experience. See below for more details:
  <table>
<tr>
<th align=“middle”>Figma design</th>
<th align=“middle”>Your design</th>
</tr>
<tr>
<td>
<img width="373" alt="Screenshot 2023-06-20 at 15 09 17" src="https://github.com/enocol/MobileFirst/assets/107192076/b7eeef12-ef03-4b65-bbb2-0b6fb4b702bf">
</td>
<td>
<img width="374" alt="Screenshot 2023-06-26 at 21 50 24" src="https://github.com/enocol/MobileFirst/assets/107192076/5f197814-13f7-4fdb-9403-70c868a609f5">
</td>
</tr>
</table>

2023-06-27 04:44 UTC, divinecharlotte approved these changes
# Hello @Team    😃 🥳 🎉 🎈 

Great Job 😄 👏 You've done it. Your project is complete!  There is nothing else to say  👍🏻 ✅ 
### To Highlight 💯


- Descriptive PR👍 
- Good implementation of the required changes 👍 
 




## Congratulations! 🎉 

<img src="https://media3.giphy.com/media/3KC2jD2QcBOSc/giphy.gif"/>

Cheers, and Happy coding!👏👏👏


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-27 04:47 UTC, merged